### ISSUE TITLE
babel-plugin-transform-class-properties and Meteor 1.5

### ISSUE THREAD

**Issue by damonmaria** [meteor/babel-preset-meteor#7]
The [changelog for Meteor 1.5](https://github.com/meteor/meteor/blob/master/History.md) mentions that the `transform-class-properties` plugin is now enabled. I was expecting therefore to see `babel-plugin-transform-class-properties` included in `babel-preset-meteor` but it's not. 

Is that correct? So if transpiling Meteor code with Babel outside of Meteor should I enable plugin `transform-class-properties` as well as preset `meteor` to match what is possible in Meteor 1.5?

**Comment by benjamn** [comment]
That plugin is enabled [in `meteor-babel`](https://github.com/meteor/babel/blob/6fb8b71e9bb1735f1b9b445a03ed4c88d773945c/options.js#L50-L52), not in this preset. So, yes, you should probably add `transform-class-properties` in addition to `babel-preset-meteor` if you're using the preset outside of Meteor.

**Comment by damonmaria** [comment]
Thanks @benjamn. Are there any other plugins in that situation?

**Comment by benjamn** [comment]
That [`options.js`](https://github.com/meteor/babel/blob/6fb8b71e9bb1735f1b9b445a03ed4c88d773945c/options.js) file has all the extra stuff.

**Comment by damonmaria** [comment]
Thanks @benjamn. Using `options.js` `getDefaults()`  directly solved all my issues and customization.
