### ISSUE TITLE
Cannot use with typescript

### ISSUE THREAD

**Issue by dobesv** [meteor/babel-preset-meteor#9]
Using the meteor preset and the typescript presets gives an error:

```
Error: Cannot combine flow and typescript plugins.
```

It seems babel no longer allows the flow and typescript plugins to be loaded at the same time.

See also:

* https://github.com/babel/babel/issues/6095
* https://github.com/facebook/create-react-app/issues/3863

**Comment by filipenevola** [comment]
I'm closing this issue because it's too old.

If you think this issue is still relevant please open a new one.

Why? We need to pay attention to all the open items so we should keep opened only items where people are involved.
